version: '1.0'
name: test
displayName: test
triggers:
  trigger: auto
  push:
    branches:
      include:
        - master
stages:
  - name: tests
    displayName: 测试
    strategy: naturally
    trigger: auto
    steps:
      - step: ut@php
        name: unit_test_php8
        displayName: PHP8 单元测试
        phpVersion: '8.1'
        commands:
          - '# 安装依赖'
          - composer install
          - '# Php单元测试默认命令'
          - composer test
          - composer phpstan
        report:
          index: index.html
        checkpoints: []
        caches: []
        notify: []
        strategy:
          retry: '0'
      - step: ut@php
        name: unit_test_php7
        displayName: PHP7 单元测试
        phpVersion: '7.4'
        commands:
          - '# 安装依赖'
          - composer install
          - '# Php单元测试默认命令'
          - composer test
          - composer phpstan
        report:
          index: index.html
        checkpoints: []
        caches: []
        notify: []
        strategy:
          retry: '0'
