# sample: https://github.com/github/docs/blob/main/.github/workflows/link-check-all.yml
name: Tests
on:
  push:
    branches:
      - 2.x
      - master
  pull_request:
    branches:
      - 2.x
      - master

jobs:
  phpunit:
    name: PHP-${{ matrix.php_version }}-${{ matrix.perfer }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php_version:
          - '7.4'
          - '8.0'
        perfer:
          - stable
          - lowest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php_version }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite
          coverage: none

      - name: Install Composer dependencies
        run: composer update --prefer-dist --no-interaction --no-suggest --prefer-${{ matrix.perfer }}

      - name: PHP version
        run: php -v

      - name: Run PHPUnit
        run: ./vendor/bin/phpunit --colors=never
